export const supportedLocales = ['ru', 'en', 'es'] as const;
export type Locale = (typeof supportedLocales)[number];
export type TranslationValues = Readonly<Record<string, string | number>>;

const en = {
  Language: 'Language',
  Avatar: 'Avatar',
  'Avatar statistics': 'Avatar statistics',
  Achievement: 'Achievement',
  Race: 'Race',
  'XP event': 'XP event',
  'Audio settings': 'Audio settings',
  'Accessibility settings': 'Accessibility settings',
  'Child data management': 'Child data management',
  'Data export': 'Data export',
  'Loading profiles…': 'Loading profiles…',
  'Could not load saved child data.': 'Could not load saved child data.',
  'GO!': 'GO!',
  '{{runner}}: {{distance}}m': '{{runner}}: {{distance}}m',
  'Leave Race': 'Leave Race',
  Confirm: 'Confirm',
  Cancel: 'Cancel',
  Save: 'Save',
  Add: 'Add',
  Back: 'Back',
  'Go Back': 'Go Back',
  Next: 'Next',
  'Try Again': 'Try Again',
  'Dismiss notification': 'Dismiss notification',
  'Loading…': 'Loading…',
  'This request could not be verified. Refresh the page and try again.':
    'This request could not be verified. Refresh the page and try again.',
  'The sign-in details are incorrect or the account is not approved yet.':
    'The sign-in details are incorrect or the account is not approved yet.',
  'Registration could not be completed. Please try again.':
    'Registration could not be completed. Please try again.',
  'Something went wrong. Please try again.': 'Something went wrong. Please try again.',
  'We couldn’t find that. Let’s go back!': 'We couldn’t find that. Let’s go back!',
  'Please log in again.': 'Please log in again.',
  'Something went wrong. Let’s try again!': 'Something went wrong. Let’s try again!',
  'Oops! Check your internet connection and try again.':
    'Oops! Check your internet connection and try again.',
  'Something went wrong.': 'Something went wrong.',
  'You have an active championship!': 'You have an active championship!',
  'Continue Championship': 'Continue Championship',
  'Start Racing': 'Start Racing',
  'My Avatars': 'My Avatars',
  Statistics: 'Statistics',
  'Log In': 'Log In',
  Email: 'Email',
  Password: 'Password',
  'Don’t have an account?': 'Don’t have an account?',
  Register: 'Register',
  'Account created. Please wait for an administrator to approve your account.':
    'Account created. Please wait for an administrator to approve your account.',
  'Already have an account?': 'Already have an account?',
  'Could not load profiles.': 'Could not load profiles.',
  'Could not create profile.': 'Could not create profile.',
  'Who’s Playing?': 'Who’s Playing?',
  'No profiles yet — add one below.': 'No profiles yet — add one below.',
  'Add a profile': 'Add a profile',
  'Profile name': 'Profile name',
  'New profile name': 'New profile name',
  Settings: 'Settings',
  Audio: 'Audio',
  'Master Volume': 'Master Volume',
  'Music Volume': 'Music Volume',
  'SFX Volume': 'SFX Volume',
  'Ambience Volume': 'Ambience Volume',
  'Voice Volume': 'Voice Volume',
  Accessibility: 'Accessibility',
  'Reduce motion': 'Reduce motion',
  'You are offline.': 'You are offline.',
  'Saved progress': 'Saved progress',
  'Last saved progress': 'Last saved progress',
  '{{races}} races completed': '{{races}} races completed',
  '{{problems}} problems answered': '{{problems}} problems answered',
  'Accuracy: {{accuracy}}': 'Accuracy: {{accuracy}}',
  'Favourite operation: {{operation}}': 'Favourite operation: {{operation}}',
  'No saved progress is available for this child.':
    'No saved progress is available for this child.',
  'Could not load saved progress.': 'Could not load saved progress.',
  'Parent Dashboard': 'Parent Dashboard',
  'Failed to load data. Please try again.': 'Failed to load data. Please try again.',
  'This Week': 'This Week',
  '{{races}} races': '{{races}} races',
  completed: 'completed',
  '{{solved}} problems solved ({{correct}} correct)':
    '{{solved}} problems solved ({{correct}} correct)',
  'Strongest operation: {{operation}}': 'Strongest operation: {{operation}}',
  'Weakest operation: {{operation}}': 'Weakest operation: {{operation}}',
  'Avg response: {{duration}} ms': 'Avg response: {{duration}} ms',
  'XP earned: {{xp}}': 'XP earned: {{xp}}',
  'All-Time Records': 'All-Time Records',
  'Total Races': 'Total Races',
  'Best Streak': 'Best Streak',
  'Best Accuracy': 'Best Accuracy',
  'Fastest Avg (ms)': 'Fastest Avg (ms)',
  'Child Data': 'Child Data',
  'Unassigned records are not visible to this child until you assign them.':
    'Unassigned records are not visible to this child until you assign them.',
  'Unassigned records': 'Unassigned records',
  'Assign selected data': 'Assign selected data',
  'No unassigned records.': 'No unassigned records.',
  'Export child data': 'Export child data',
  'Delete child profile and data': 'Delete child profile and data',
  'Select a child profile to manage child data.': 'Select a child profile to manage child data.',
  '{{count}} records assigned to this child.': '{{count}} records assigned to this child.',
  'Could not load unassigned child data.': 'Could not load unassigned child data.',
  'Could not assign the selected records. Refresh and try again.':
    'Could not assign the selected records. Refresh and try again.',
  'Could not export this child data.': 'Could not export this child data.',
  'Could not delete this child profile.': 'Could not delete this child profile.',
  'The profile was deleted, but saved offline data could not be removed from this device.':
    'The profile was deleted, but saved offline data could not be removed from this device.',
  'Delete this child profile and all its data?': 'Delete this child profile and all its data?',
  Export: 'Export',
  'Export race history (CSV)': 'Export race history (CSV)',
  'Could not load avatars.': 'Could not load avatars.',
  'Could not update favourite. Try again.': 'Could not update favourite. Try again.',
  'Could not rename avatar. Try again.': 'Could not rename avatar. Try again.',
  'Could not regenerate portrait. Try again.': 'Could not regenerate portrait. Try again.',
  'Could not delete avatar. Try again.': 'Could not delete avatar. Try again.',
  'Your Avatars': 'Your Avatars',
  'You don’t have any avatars yet. Create your first one!':
    'You don’t have any avatars yet. Create your first one!',
  'Create Your First Avatar': 'Create Your First Avatar',
  'Avatar update error': 'Avatar update error',
  Dismiss: 'Dismiss',
  '+ New Avatar': '+ New Avatar',
  'Add to favourites': 'Add to favourites',
  'Remove from favourites': 'Remove from favourites',
  'Rename avatar': 'Rename avatar',
  'Manage avatar': 'Manage avatar',
  Rename: 'Rename',
  Regenerate: 'Regenerate',
  Delete: 'Delete',
  'Delete avatar?': 'Delete avatar?',
  'This cannot be undone.': 'This cannot be undone.',
  'Generating…': 'Generating…',
  'Hmm, something went wobbly.': 'Hmm, something went wobbly.',
  'Internet required to create avatars.': 'Internet required to create avatars.',
  'Choose Your Animal': 'Choose Your Animal',
  'Choose Colours': 'Choose Colours',
  'Fur colour': 'Fur colour',
  'Eye colour': 'Eye colour',
  'Fur colour {{color}}': 'Fur colour {{color}}',
  'Eye colour {{color}}': 'Eye colour {{color}}',
  'Choose Your Style': 'Choose Your Style',
  Hairstyle: 'Hairstyle',
  'Accessories (optional)': 'Accessories (optional)',
  'Choose Clothing': 'Choose Clothing',
  'Top colour': 'Top colour',
  'Shorts colour': 'Shorts colour',
  'Top colour {{color}}': 'Top colour {{color}}',
  'Shorts colour {{color}}': 'Shorts colour {{color}}',
  'Creating Your Avatar…': 'Creating Your Avatar…',
  'Looks like we lost the signal. Check your connection!':
    'Looks like we lost the signal. Check your connection!',
  'Our AI artist is painting your character. This takes about 20 seconds.':
    'Our AI artist is painting your character. This takes about 20 seconds.',
  fox: 'fox',
  rabbit: 'rabbit',
  bear: 'bear',
  cat: 'cat',
  mouse: 'mouse',
  panda: 'panda',
  short: 'short',
  long: 'long',
  curly: 'curly',
  braided: 'braided',
  headband: 'headband',
  glasses: 'glasses',
  hat: 'hat',
  scarf: 'scarf',
  'Quick Race': 'Quick Race',
  Championship: 'Championship',
  Training: 'Training',
  Duel: 'Duel',
  offline: 'offline',
  'Saved Tier 6 settings could not be loaded.': 'Saved Tier 6 settings could not be loaded.',
  'Select a child profile before Training.': 'Select a child profile before Training.',
  'No saved avatar or offline Training session is available.':
    'No saved avatar or offline Training session is available.',
  'Statistics could not be refreshed for offline use.':
    'Statistics could not be refreshed for offline use.',
  'Offline Training is not ready. You can still play while online.':
    'Offline Training is not ready. You can still play while online.',
  'Settings could not be saved.': 'Settings could not be saved.',
  'Loading your avatars…': 'Loading your avatars…',
  'Race Setup': 'Race Setup',
  Mode: 'Mode',
  'Number of Races': 'Number of Races',
  Opponents: 'Opponents',
  'Difficulty (Tier 1 = easiest)': 'Difficulty (Tier 1 = easiest)',
  'Tier {{tier}}': 'Tier {{tier}}',
  'Custom Tier 6 settings': 'Custom Tier 6 settings',
  'Select one or more operations and an operand range from 1 to 100.':
    'Select one or more operations and an operand range from 1 to 100.',
  addition: 'addition',
  subtraction: 'subtraction',
  multiplication: 'multiplication',
  division: 'division',
  'Minimum operand': 'Minimum operand',
  'Maximum operand': 'Maximum operand',
  'Saving…': 'Saving…',
  'Save Tier 6 settings': 'Save Tier 6 settings',
  'Tier 6 settings saved.': 'Tier 6 settings saved.',
  'Racing as': 'Racing as',
  'Setting up…': 'Setting up…',
  'Start Race': 'Start Race',
  'Leave Race?': 'Leave Race?',
  'Your progress will be lost if you leave now.': 'Your progress will be lost if you leave now.',
  Leave: 'Leave',
  'Race track': 'Race track',
  You: 'You',
  'CPU {{number}}': 'CPU {{number}}',
  '{{distance}}m': '{{distance}}m',
  'What is {{first}} {{operator}} {{second}}?': 'What is {{first}} {{operator}} {{second}}?',
  Submit: 'Submit',
  'Problems answered: {{count}}': 'Problems answered: {{count}}',
  'Obstacle {{current}} of {{total}}': 'Obstacle {{current}} of {{total}}',
  'The answer could not be saved.': 'The answer could not be saved.',
  'Finish Training': 'Finish Training',
  'Level Up!': 'Level Up!',
  'You reached Level {{level}}!': 'You reached Level {{level}}!',
  'Achievement: {{title}}': 'Achievement: {{title}}',
  'Training Complete': 'Training Complete',
  'Race Finished!': 'Race Finished!',
  Place: 'Place',
  Runner: 'Runner',
  Distance: 'Distance',
  Correct: 'Correct',
  XP: 'XP',
  'Runner {{number}}': 'Runner {{number}}',
  'Couldn’t save results.': 'Couldn’t save results.',
  Retry: 'Retry',
  'Training results are saved on this device and will sync when online.':
    'Training results are saved on this device and will sync when online.',
  'Race Again': 'Race Again',
  'View Championship': 'View Championship',
  Home: 'Home',
  'Loading standings…': 'Loading standings…',
  'Championship not found.': 'Championship not found.',
  'Race {{completed}} of {{total}} complete': 'Race {{completed}} of {{total}} complete',
  Position: 'Position',
  Points: 'Points',
  Podiums: 'Podiums',
  Opponent: 'Opponent',
  'Championship Complete!': 'Championship Complete!',
  'Play Again': 'Play Again',
  'Start Next Race': 'Start Next Race',
  'Failed to load statistics. Please try again.': 'Failed to load statistics. Please try again.',
  'Player statistics': 'Player statistics',
  'All-Time': 'All-Time',
  Races: 'Races',
  Accuracy: 'Accuracy',
  'Favourite operation': 'Favourite operation',
  'Avg response (ms)': 'Avg response (ms)',
  'Best streak': 'Best streak',
  'Race history': 'Race history',
  'Recent Races': 'Recent Races',
  'No races yet.': 'No races yet.',
  Score: 'Score',
  Streak: 'Streak',
  Previous: 'Previous',
  'Page {{page}} of {{total}}': 'Page {{page}} of {{total}}',
  Level: 'Level',
  'Level {{level}} — {{current}} of {{max}} XP': 'Level {{level}} — {{current}} of {{max}} XP',
  'Syncing saved Training results…': 'Syncing saved Training results…',
  'Saved Training results are synced.': 'Saved Training results are synced.',
  'Training results could not sync. They remain saved on this device.':
    'Training results could not sync. They remain saved on this device.',
  'Off to the Races!': 'Off to the Races!',
  'Complete your first race.': 'Complete your first race.',
  'Perfect Score': 'Perfect Score',
  'Answer all 8 problems correctly in a single race.':
    'Answer all 8 problems correctly in a single race.',
  'Podium Finisher': 'Podium Finisher',
  'Finish in the top 3 in a race.': 'Finish in the top 3 in a race.',
  Champion: 'Champion',
  'Finish in 1st place in a race.': 'Finish in 1st place in a race.',
  'Rising Star': 'Rising Star',
  'Reach level 5.': 'Reach level 5.',
  'Veteran Racer': 'Veteran Racer',
  'Reach level 10.': 'Reach level 10.',
  'Math Legend': 'Math Legend',
  'Reach level 20.': 'Reach level 20.',
  'Speed Demon': 'Speed Demon',
  'Win a race with an average response time under 500ms.':
    'Win a race with an average response time under 500ms.',
};

type TranslationKey = keyof typeof en;

const ru: Record<TranslationKey, string> = {
  Language: 'Язык',
  Avatar: 'Персонаж',
  'Avatar statistics': 'Статистика персонажа',
  Achievement: 'Достижение',
  Race: 'Заезд',
  'XP event': 'Событие получения опыта',
  'Audio settings': 'Настройки звука',
  'Accessibility settings': 'Настройки специальных возможностей',
  'Child data management': 'Управление данными ребёнка',
  'Data export': 'Экспорт данных',
  'Loading profiles…': 'Загрузка профилей…',
  'Could not load saved child data.': 'Не удалось загрузить сохранённые данные ребёнка.',
  'GO!': 'Вперёд!',
  '{{runner}}: {{distance}}m': '{{runner}}: {{distance}}м',
  'Leave Race': 'Покинуть гонку',
  Confirm: 'Подтвердить',
  Cancel: 'Отмена',
  Save: 'Сохранить',
  Add: 'Добавить',
  Back: 'Назад',
  'Go Back': 'Вернуться',
  Next: 'Далее',
  'Try Again': 'Попробовать снова',
  'Dismiss notification': 'Закрыть уведомление',
  'Loading…': 'Загрузка…',
  'This request could not be verified. Refresh the page and try again.':
    'Не удалось проверить запрос. Обновите страницу и попробуйте снова.',
  'The sign-in details are incorrect or the account is not approved yet.':
    'Неверный email или пароль, либо аккаунт ещё не одобрен.',
  'Registration could not be completed. Please try again.':
    'Не удалось зарегистрироваться. Попробуйте ещё раз.',
  'Something went wrong. Please try again.': 'Что-то пошло не так. Попробуйте ещё раз.',
  'We couldn’t find that. Let’s go back!': 'Не удалось найти. Давайте вернёмся назад!',
  'Please log in again.': 'Войдите в аккаунт ещё раз.',
  'Something went wrong. Let’s try again!': 'Что-то пошло не так. Давайте попробуем ещё раз!',
  'Oops! Check your internet connection and try again.':
    'Ой! Проверьте подключение к интернету и попробуйте снова.',
  'Something went wrong.': 'Что-то пошло не так.',
  'You have an active championship!': 'У вас продолжается чемпионат!',
  'Continue Championship': 'Продолжить чемпионат',
  'Start Racing': 'Начать гонку',
  'My Avatars': 'Мои персонажи',
  Statistics: 'Статистика',
  'Log In': 'Войти',
  Email: 'Электронная почта',
  Password: 'Пароль',
  'Don’t have an account?': 'Нет аккаунта?',
  Register: 'Зарегистрироваться',
  'Account created. Please wait for an administrator to approve your account.':
    'Аккаунт создан. Дождитесь, пока администратор его одобрит.',
  'Already have an account?': 'Уже есть аккаунт?',
  'Could not load profiles.': 'Не удалось загрузить профили.',
  'Could not create profile.': 'Не удалось создать профиль.',
  'Who’s Playing?': 'Кто будет играть?',
  'No profiles yet — add one below.': 'Пока нет профилей — добавьте профиль ниже.',
  'Add a profile': 'Добавить профиль',
  'Profile name': 'Имя профиля',
  'New profile name': 'Имя нового профиля',
  Settings: 'Настройки',
  Audio: 'Звук',
  'Master Volume': 'Общая громкость',
  'Music Volume': 'Громкость музыки',
  'SFX Volume': 'Громкость эффектов',
  'Ambience Volume': 'Громкость окружения',
  'Voice Volume': 'Громкость голоса',
  Accessibility: 'Специальные возможности',
  'Reduce motion': 'Уменьшить анимацию',
  'You are offline.': 'Нет подключения к интернету.',
  'Saved progress': 'Сохранённый прогресс',
  'Last saved progress': 'Последний сохранённый прогресс',
  '{{races}} races completed': 'Завершено заездов: {{races}}',
  '{{problems}} problems answered': 'Решено примеров: {{problems}}',
  'Accuracy: {{accuracy}}': 'Точность: {{accuracy}}',
  'Favourite operation: {{operation}}': 'Любимое действие: {{operation}}',
  'No saved progress is available for this child.': 'Для этого ребёнка нет сохранённого прогресса.',
  'Could not load saved progress.': 'Не удалось загрузить сохранённый прогресс.',
  'Parent Dashboard': 'Панель родителя',
  'Failed to load data. Please try again.': 'Не удалось загрузить данные. Попробуйте ещё раз.',
  'This Week': 'За эту неделю',
  '{{races}} races': 'Заездов: {{races}}',
  completed: 'завершено',
  '{{solved}} problems solved ({{correct}} correct)':
    'Решено примеров: {{solved}} (верно: {{correct}})',
  'Strongest operation: {{operation}}': 'Лучше всего получается: {{operation}}',
  'Weakest operation: {{operation}}': 'Нужно потренировать: {{operation}}',
  'Avg response: {{duration}} ms': 'Среднее время ответа: {{duration}} мс',
  'XP earned: {{xp}}': 'Получено опыта: {{xp}}',
  'All-Time Records': 'Рекорды за всё время',
  'Total Races': 'Всего заездов',
  'Best Streak': 'Лучшая серия',
  'Best Accuracy': 'Лучшая точность',
  'Fastest Avg (ms)': 'Лучшее среднее время (мс)',
  'Child Data': 'Данные ребёнка',
  'Unassigned records are not visible to this child until you assign them.':
    'Ребёнок не увидит эти записи, пока вы не назначите их ему.',
  'Unassigned records': 'Неназначенные записи',
  'Assign selected data': 'Назначить выбранные данные',
  'No unassigned records.': 'Нет неназначенных записей.',
  'Export child data': 'Экспортировать данные ребёнка',
  'Delete child profile and data': 'Удалить профиль и данные ребёнка',
  'Select a child profile to manage child data.':
    'Выберите профиль ребёнка, чтобы управлять его данными.',
  '{{count}} records assigned to this child.': 'Назначено записей: {{count}}.',
  'Could not load unassigned child data.': 'Не удалось загрузить неназначенные данные ребёнка.',
  'Could not assign the selected records. Refresh and try again.':
    'Не удалось назначить выбранные записи. Обновите страницу и попробуйте снова.',
  'Could not export this child data.': 'Не удалось экспортировать данные ребёнка.',
  'Could not delete this child profile.': 'Не удалось удалить профиль ребёнка.',
  'The profile was deleted, but saved offline data could not be removed from this device.':
    'Профиль удалён, но сохранённые на устройстве данные офлайн удалить не удалось.',
  'Delete this child profile and all its data?': 'Удалить профиль ребёнка и все его данные?',
  Export: 'Экспорт',
  'Export race history (CSV)': 'Экспортировать историю заездов (CSV)',
  'Could not load avatars.': 'Не удалось загрузить персонажей.',
  'Could not update favourite. Try again.': 'Не удалось изменить избранное. Попробуйте снова.',
  'Could not rename avatar. Try again.': 'Не удалось переименовать персонажа. Попробуйте снова.',
  'Could not regenerate portrait. Try again.':
    'Не удалось создать новый портрет. Попробуйте снова.',
  'Could not delete avatar. Try again.': 'Не удалось удалить персонажа. Попробуйте снова.',
  'Your Avatars': 'Ваши персонажи',
  'You don’t have any avatars yet. Create your first one!':
    'У вас пока нет персонажей. Создайте первого!',
  'Create Your First Avatar': 'Создать первого персонажа',
  'Avatar update error': 'Ошибка обновления персонажа',
  Dismiss: 'Закрыть',
  '+ New Avatar': '+ Новый персонаж',
  'Add to favourites': 'Добавить в избранное',
  'Remove from favourites': 'Убрать из избранного',
  'Rename avatar': 'Переименовать персонажа',
  'Manage avatar': 'Управление персонажем',
  Rename: 'Переименовать',
  Regenerate: 'Создать портрет заново',
  Delete: 'Удалить',
  'Delete avatar?': 'Удалить персонажа?',
  'This cannot be undone.': 'Это действие нельзя отменить.',
  'Generating…': 'Создаётся…',
  'Hmm, something went wobbly.': 'Хм, что-то пошло не так.',
  'Internet required to create avatars.': 'Для создания персонажей нужен интернет.',
  'Choose Your Animal': 'Выберите животное',
  'Choose Colours': 'Выберите цвета',
  'Fur colour': 'Цвет шерсти',
  'Eye colour': 'Цвет глаз',
  'Fur colour {{color}}': 'Цвет шерсти {{color}}',
  'Eye colour {{color}}': 'Цвет глаз {{color}}',
  'Choose Your Style': 'Выберите стиль',
  Hairstyle: 'Причёска',
  'Accessories (optional)': 'Аксессуары (необязательно)',
  'Choose Clothing': 'Выберите одежду',
  'Top colour': 'Цвет футболки',
  'Shorts colour': 'Цвет шорт',
  'Top colour {{color}}': 'Цвет футболки {{color}}',
  'Shorts colour {{color}}': 'Цвет шорт {{color}}',
  'Creating Your Avatar…': 'Создаём персонажа…',
  'Looks like we lost the signal. Check your connection!':
    'Похоже, связь прервалась. Проверьте подключение к интернету!',
  'Our AI artist is painting your character. This takes about 20 seconds.':
    'Наш художник с ИИ рисует вашего персонажа. Это займёт около 20 секунд.',
  fox: 'лиса',
  rabbit: 'кролик',
  bear: 'медведь',
  cat: 'кошка',
  mouse: 'мышь',
  panda: 'панда',
  short: 'короткие',
  long: 'длинные',
  curly: 'кудрявые',
  braided: 'заплетённые',
  headband: 'повязка',
  glasses: 'очки',
  hat: 'шляпа',
  scarf: 'шарф',
  'Quick Race': 'Быстрый заезд',
  Championship: 'Чемпионат',
  Training: 'Тренировка',
  Duel: 'Дуэль',
  offline: 'офлайн',
  'Saved Tier 6 settings could not be loaded.':
    'Не удалось загрузить сохранённые настройки уровня 6.',
  'Select a child profile before Training.': 'Перед тренировкой выберите профиль ребёнка.',
  'No saved avatar or offline Training session is available.':
    'Нет сохранённого персонажа или офлайн-тренировки.',
  'Statistics could not be refreshed for offline use.':
    'Не удалось обновить статистику для офлайн-режима.',
  'Offline Training is not ready. You can still play while online.':
    'Офлайн-тренировка не готова. Пока можно играть с подключением к интернету.',
  'Settings could not be saved.': 'Не удалось сохранить настройки.',
  'Loading your avatars…': 'Загружаем персонажей…',
  'Race Setup': 'Настройка заезда',
  Mode: 'Режим',
  'Number of Races': 'Количество заездов',
  Opponents: 'Соперники',
  'Difficulty (Tier 1 = easiest)': 'Сложность (уровень 1 — самый лёгкий)',
  'Tier {{tier}}': 'Уровень {{tier}}',
  'Custom Tier 6 settings': 'Настройки уровня 6',
  'Select one or more operations and an operand range from 1 to 100.':
    'Выберите действия и диапазон чисел от 1 до 100.',
  addition: 'сложение',
  subtraction: 'вычитание',
  multiplication: 'умножение',
  division: 'деление',
  'Minimum operand': 'Минимальное число',
  'Maximum operand': 'Максимальное число',
  'Saving…': 'Сохраняем…',
  'Save Tier 6 settings': 'Сохранить настройки уровня 6',
  'Tier 6 settings saved.': 'Настройки уровня 6 сохранены.',
  'Racing as': 'Персонаж',
  'Setting up…': 'Подготавливаем…',
  'Start Race': 'Начать заезд',
  'Leave Race?': 'Покинуть заезд?',
  'Your progress will be lost if you leave now.': 'Если вы уйдёте сейчас, прогресс будет потерян.',
  Leave: 'Покинуть',
  'Race track': 'Гоночная трасса',
  You: 'Вы',
  'CPU {{number}}': 'Компьютер {{number}}',
  '{{distance}}m': '{{distance}}м',
  'What is {{first}} {{operator}} {{second}}?': 'Сколько будет {{first}} {{operator}} {{second}}?',
  Submit: 'Ответить',
  'Problems answered: {{count}}': 'Решено примеров: {{count}}',
  'Obstacle {{current}} of {{total}}': 'Препятствие {{current}} из {{total}}',
  'The answer could not be saved.': 'Не удалось сохранить ответ.',
  'Finish Training': 'Завершить тренировку',
  'Level Up!': 'Новый уровень!',
  'You reached Level {{level}}!': 'Вы достигли {{level}} уровня!',
  'Achievement: {{title}}': 'Достижение: {{title}}',
  'Training Complete': 'Тренировка завершена',
  'Race Finished!': 'Заезд завершён!',
  Place: 'Место',
  Runner: 'Участник',
  Distance: 'Дистанция',
  Correct: 'Верно',
  XP: 'Опыт',
  'Runner {{number}}': 'Участник {{number}}',
  'Couldn’t save results.': 'Не удалось сохранить результаты.',
  Retry: 'Повторить',
  'Training results are saved on this device and will sync when online.':
    'Результаты тренировки сохранены на устройстве и синхронизируются при подключении к интернету.',
  'Race Again': 'Ещё заезд',
  'View Championship': 'Открыть чемпионат',
  Home: 'На главную',
  'Loading standings…': 'Загружаем таблицу результатов…',
  'Championship not found.': 'Чемпионат не найден.',
  'Race {{completed}} of {{total}} complete': 'Завершён заезд {{completed}} из {{total}}',
  Position: 'Место',
  Points: 'Очки',
  Podiums: 'Призовые места',
  Opponent: 'Соперник',
  'Championship Complete!': 'Чемпионат завершён!',
  'Play Again': 'Играть снова',
  'Start Next Race': 'Начать следующий заезд',
  'Failed to load statistics. Please try again.':
    'Не удалось загрузить статистику. Попробуйте ещё раз.',
  'Player statistics': 'Статистика игрока',
  'All-Time': 'За всё время',
  Races: 'Заезды',
  Accuracy: 'Точность',
  'Favourite operation': 'Любимое действие',
  'Avg response (ms)': 'Среднее время ответа (мс)',
  'Best streak': 'Лучшая серия',
  'Race history': 'История заездов',
  'Recent Races': 'Последние заезды',
  'No races yet.': 'Заездов пока нет.',
  Score: 'Результат',
  Streak: 'Серия',
  Previous: 'Назад',
  'Page {{page}} of {{total}}': 'Страница {{page}} из {{total}}',
  Level: 'Уровень',
  'Level {{level}} — {{current}} of {{max}} XP': 'Уровень {{level}} — {{current}} из {{max}} опыта',
  'Syncing saved Training results…': 'Синхронизируем результаты тренировки…',
  'Saved Training results are synced.': 'Результаты тренировки синхронизированы.',
  'Training results could not sync. They remain saved on this device.':
    'Не удалось синхронизировать результаты тренировки. Они останутся на этом устройстве.',
  'Off to the Races!': 'К гонке готовы!',
  'Complete your first race.': 'Завершите свой первый заезд.',
  'Perfect Score': 'Идеальный результат',
  'Answer all 8 problems correctly in a single race.':
    'Решите все 8 примеров без ошибок в одном заезде.',
  'Podium Finisher': 'На пьедестале',
  'Finish in the top 3 in a race.': 'Займите одно из трёх первых мест в заезде.',
  Champion: 'Чемпион',
  'Finish in 1st place in a race.': 'Займите первое место в заезде.',
  'Rising Star': 'Восходящая звезда',
  'Reach level 5.': 'Достигните 5-го уровня.',
  'Veteran Racer': 'Опытный гонщик',
  'Reach level 10.': 'Достигните 10-го уровня.',
  'Math Legend': 'Легенда математики',
  'Reach level 20.': 'Достигните 20-го уровня.',
  'Speed Demon': 'Молниеносный гонщик',
  'Win a race with an average response time under 500ms.':
    'Победите в заезде со средним временем ответа меньше 500 мс.',
};

const es: Record<TranslationKey, string> = {
  Language: 'Idioma',
  Avatar: 'Avatar',
  'Avatar statistics': 'Estadísticas del avatar',
  Achievement: 'Logro',
  Race: 'Carrera',
  'XP event': 'Evento de experiencia',
  'Audio settings': 'Ajustes de audio',
  'Accessibility settings': 'Ajustes de accesibilidad',
  'Child data management': 'Gestión de datos del menor',
  'Data export': 'Exportación de datos',
  'Loading profiles…': 'Cargando perfiles…',
  'Could not load saved child data.': 'No se pudieron cargar los datos guardados.',
  'GO!': '¡Vamos!',
  '{{runner}}: {{distance}}m': '{{runner}}: {{distance}}m',
  'Leave Race': 'Abandonar carrera',
  Confirm: 'Confirmar',
  Cancel: 'Cancelar',
  Save: 'Guardar',
  Add: 'Añadir',
  Back: 'Atrás',
  'Go Back': 'Volver',
  Next: 'Siguiente',
  'Try Again': 'Intentar de nuevo',
  'Dismiss notification': 'Cerrar notificación',
  'Loading…': 'Cargando…',
  'This request could not be verified. Refresh the page and try again.':
    'No se pudo verificar la solicitud. Actualiza la página e inténtalo de nuevo.',
  'The sign-in details are incorrect or the account is not approved yet.':
    'El correo o la contraseña no son correctos, o la cuenta aún no está aprobada.',
  'Registration could not be completed. Please try again.':
    'No se pudo completar el registro. Inténtalo de nuevo.',
  'Something went wrong. Please try again.': 'Algo salió mal. Inténtalo de nuevo.',
  'We couldn’t find that. Let’s go back!': 'No encontramos eso. ¡Volvamos atrás!',
  'Please log in again.': 'Vuelve a iniciar sesión.',
  'Something went wrong. Let’s try again!': 'Algo salió mal. ¡Intentémoslo de nuevo!',
  'Oops! Check your internet connection and try again.':
    '¡Vaya! Comprueba tu conexión a Internet e inténtalo de nuevo.',
  'Something went wrong.': 'Algo salió mal.',
  'You have an active championship!': '¡Tienes un campeonato en curso!',
  'Continue Championship': 'Continuar campeonato',
  'Start Racing': 'Empezar a correr',
  'My Avatars': 'Mis avatares',
  Statistics: 'Estadísticas',
  'Log In': 'Iniciar sesión',
  Email: 'Correo electrónico',
  Password: 'Contraseña',
  'Don’t have an account?': '¿No tienes una cuenta?',
  Register: 'Registrarse',
  'Account created. Please wait for an administrator to approve your account.':
    'Cuenta creada. Espera a que un administrador la apruebe.',
  'Already have an account?': '¿Ya tienes una cuenta?',
  'Could not load profiles.': 'No se pudieron cargar los perfiles.',
  'Could not create profile.': 'No se pudo crear el perfil.',
  'Who’s Playing?': '¿Quién va a jugar?',
  'No profiles yet — add one below.': 'Aún no hay perfiles: añade uno abajo.',
  'Add a profile': 'Añadir un perfil',
  'Profile name': 'Nombre del perfil',
  'New profile name': 'Nombre del nuevo perfil',
  Settings: 'Ajustes',
  Audio: 'Audio',
  'Master Volume': 'Volumen general',
  'Music Volume': 'Volumen de la música',
  'SFX Volume': 'Volumen de efectos',
  'Ambience Volume': 'Volumen del ambiente',
  'Voice Volume': 'Volumen de voz',
  Accessibility: 'Accesibilidad',
  'Reduce motion': 'Reducir movimiento',
  'You are offline.': 'No tienes conexión.',
  'Saved progress': 'Progreso guardado',
  'Last saved progress': 'Último progreso guardado',
  '{{races}} races completed': 'Carreras completadas: {{races}}',
  '{{problems}} problems answered': 'Problemas respondidos: {{problems}}',
  'Accuracy: {{accuracy}}': 'Precisión: {{accuracy}}',
  'Favourite operation: {{operation}}': 'Operación favorita: {{operation}}',
  'No saved progress is available for this child.': 'No hay progreso guardado para este niño.',
  'Could not load saved progress.': 'No se pudo cargar el progreso guardado.',
  'Parent Dashboard': 'Panel para padres',
  'Failed to load data. Please try again.': 'No se pudieron cargar los datos. Inténtalo de nuevo.',
  'This Week': 'Esta semana',
  '{{races}} races': 'Carreras: {{races}}',
  completed: 'completadas',
  '{{solved}} problems solved ({{correct}} correct)':
    'Problemas resueltos: {{solved}} (correctos: {{correct}})',
  'Strongest operation: {{operation}}': 'Mejor operación: {{operation}}',
  'Weakest operation: {{operation}}': 'Operación para practicar: {{operation}}',
  'Avg response: {{duration}} ms': 'Tiempo medio de respuesta: {{duration}} ms',
  'XP earned: {{xp}}': 'Experiencia obtenida: {{xp}}',
  'All-Time Records': 'Récords de todos los tiempos',
  'Total Races': 'Carreras totales',
  'Best Streak': 'Mejor racha',
  'Best Accuracy': 'Mejor precisión',
  'Fastest Avg (ms)': 'Mejor media (ms)',
  'Child Data': 'Datos del niño',
  'Unassigned records are not visible to this child until you assign them.':
    'El niño no verá estos registros hasta que se los asignes.',
  'Unassigned records': 'Registros sin asignar',
  'Assign selected data': 'Asignar datos seleccionados',
  'No unassigned records.': 'No hay registros sin asignar.',
  'Export child data': 'Exportar datos del niño',
  'Delete child profile and data': 'Eliminar perfil y datos del niño',
  'Select a child profile to manage child data.':
    'Selecciona un perfil para administrar los datos del niño.',
  '{{count}} records assigned to this child.': 'Registros asignados: {{count}}.',
  'Could not load unassigned child data.': 'No se pudieron cargar los datos sin asignar.',
  'Could not assign the selected records. Refresh and try again.':
    'No se pudieron asignar los registros. Actualiza la página e inténtalo de nuevo.',
  'Could not export this child data.': 'No se pudieron exportar los datos del niño.',
  'Could not delete this child profile.': 'No se pudo eliminar el perfil del niño.',
  'The profile was deleted, but saved offline data could not be removed from this device.':
    'Se eliminó el perfil, pero no se pudieron borrar de este dispositivo los datos guardados sin conexión.',
  'Delete this child profile and all its data?':
    '¿Eliminar este perfil del niño y todos sus datos?',
  Export: 'Exportar',
  'Export race history (CSV)': 'Exportar el historial de carreras (CSV)',
  'Could not load avatars.': 'No se pudieron cargar los avatares.',
  'Could not update favourite. Try again.':
    'No se pudo actualizar el favorito. Inténtalo de nuevo.',
  'Could not rename avatar. Try again.': 'No se pudo cambiar el nombre. Inténtalo de nuevo.',
  'Could not regenerate portrait. Try again.': 'No se pudo crear otro retrato. Inténtalo de nuevo.',
  'Could not delete avatar. Try again.': 'No se pudo eliminar el avatar. Inténtalo de nuevo.',
  'Your Avatars': 'Tus avatares',
  'You don’t have any avatars yet. Create your first one!':
    'Aún no tienes avatares. ¡Crea el primero!',
  'Create Your First Avatar': 'Crear tu primer avatar',
  'Avatar update error': 'Error al actualizar el avatar',
  Dismiss: 'Cerrar',
  '+ New Avatar': '+ Nuevo avatar',
  'Add to favourites': 'Añadir a favoritos',
  'Remove from favourites': 'Quitar de favoritos',
  'Rename avatar': 'Cambiar nombre del avatar',
  'Manage avatar': 'Administrar avatar',
  Rename: 'Cambiar nombre',
  Regenerate: 'Regenerar',
  Delete: 'Eliminar',
  'Delete avatar?': '¿Eliminar el avatar?',
  'This cannot be undone.': 'Esta acción no se puede deshacer.',
  'Generating…': 'Generando…',
  'Hmm, something went wobbly.': 'Vaya, algo salió mal.',
  'Internet required to create avatars.': 'Se necesita Internet para crear avatares.',
  'Choose Your Animal': 'Elige tu animal',
  'Choose Colours': 'Elige los colores',
  'Fur colour': 'Color del pelaje',
  'Eye colour': 'Color de ojos',
  'Fur colour {{color}}': 'Color del pelaje {{color}}',
  'Eye colour {{color}}': 'Color de ojos {{color}}',
  'Choose Your Style': 'Elige tu estilo',
  Hairstyle: 'Peinado',
  'Accessories (optional)': 'Accesorios (opcional)',
  'Choose Clothing': 'Elige la ropa',
  'Top colour': 'Color de la camiseta',
  'Shorts colour': 'Color del pantalón corto',
  'Top colour {{color}}': 'Color de la camiseta {{color}}',
  'Shorts colour {{color}}': 'Color del pantalón corto {{color}}',
  'Creating Your Avatar…': 'Creando tu avatar…',
  'Looks like we lost the signal. Check your connection!':
    'Parece que perdimos la señal. ¡Comprueba tu conexión!',
  'Our AI artist is painting your character. This takes about 20 seconds.':
    'Nuestro artista con IA está dibujando tu personaje. Tardará unos 20 segundos.',
  fox: 'zorro',
  rabbit: 'conejo',
  bear: 'oso',
  cat: 'gato',
  mouse: 'ratón',
  panda: 'panda',
  short: 'corto',
  long: 'largo',
  curly: 'rizado',
  braided: 'trenzado',
  headband: 'diadema',
  glasses: 'gafas',
  hat: 'sombrero',
  scarf: 'bufanda',
  'Quick Race': 'Carrera rápida',
  Championship: 'Campeonato',
  Training: 'Entrenamiento',
  Duel: 'Duelo',
  offline: 'sin conexión',
  'Saved Tier 6 settings could not be loaded.':
    'No se pudieron cargar los ajustes guardados del nivel 6.',
  'Select a child profile before Training.': 'Selecciona un perfil antes de entrenar.',
  'No saved avatar or offline Training session is available.':
    'No hay un avatar guardado ni una sesión de entrenamiento sin conexión disponible.',
  'Statistics could not be refreshed for offline use.':
    'No se pudieron actualizar las estadísticas para usarlas sin conexión.',
  'Offline Training is not ready. You can still play while online.':
    'El entrenamiento sin conexión no está listo. Puedes jugar con conexión.',
  'Settings could not be saved.': 'No se pudieron guardar los ajustes.',
  'Loading your avatars…': 'Cargando tus avatares…',
  'Race Setup': 'Preparar carrera',
  Mode: 'Modo',
  'Number of Races': 'Número de carreras',
  Opponents: 'Rivales',
  'Difficulty (Tier 1 = easiest)': 'Dificultad (nivel 1 = el más fácil)',
  'Tier {{tier}}': 'Nivel {{tier}}',
  'Custom Tier 6 settings': 'Ajustes personalizados del nivel 6',
  'Select one or more operations and an operand range from 1 to 100.':
    'Selecciona una o más operaciones y un rango de números del 1 al 100.',
  addition: 'suma',
  subtraction: 'resta',
  multiplication: 'multiplicación',
  division: 'división',
  'Minimum operand': 'Número mínimo',
  'Maximum operand': 'Número máximo',
  'Saving…': 'Guardando…',
  'Save Tier 6 settings': 'Guardar ajustes del nivel 6',
  'Tier 6 settings saved.': 'Ajustes del nivel 6 guardados.',
  'Racing as': 'Corres con',
  'Setting up…': 'Preparando…',
  'Start Race': 'Empezar carrera',
  'Leave Race?': '¿Salir de la carrera?',
  'Your progress will be lost if you leave now.': 'Perderás el progreso si sales ahora.',
  Leave: 'Salir',
  'Race track': 'Pista de carreras',
  You: 'Tú',
  'CPU {{number}}': 'Ordenador {{number}}',
  '{{distance}}m': '{{distance}}m',
  'What is {{first}} {{operator}} {{second}}?': '¿Cuánto es {{first}} {{operator}} {{second}}?',
  Submit: 'Enviar',
  'Problems answered: {{count}}': 'Problemas respondidos: {{count}}',
  'Obstacle {{current}} of {{total}}': 'Obstáculo {{current}} de {{total}}',
  'The answer could not be saved.': 'No se pudo guardar la respuesta.',
  'Finish Training': 'Terminar entrenamiento',
  'Level Up!': '¡Subes de nivel!',
  'You reached Level {{level}}!': '¡Has alcanzado el nivel {{level}}!',
  'Achievement: {{title}}': 'Logro: {{title}}',
  'Training Complete': 'Entrenamiento terminado',
  'Race Finished!': '¡Carrera terminada!',
  Place: 'Puesto',
  Runner: 'Corredor',
  Distance: 'Distancia',
  Correct: 'Correctas',
  XP: 'XP',
  'Runner {{number}}': 'Corredor {{number}}',
  'Couldn’t save results.': 'No se pudieron guardar los resultados.',
  Retry: 'Reintentar',
  'Training results are saved on this device and will sync when online.':
    'Los resultados del entrenamiento están guardados en este dispositivo y se sincronizarán al conectarte.',
  'Race Again': 'Correr otra vez',
  'View Championship': 'Ver campeonato',
  Home: 'Inicio',
  'Loading standings…': 'Cargando clasificación…',
  'Championship not found.': 'No se encontró el campeonato.',
  'Race {{completed}} of {{total}} complete': 'Carrera {{completed}} de {{total}} completada',
  Position: 'Posición',
  Points: 'Puntos',
  Podiums: 'Podios',
  Opponent: 'Rival',
  'Championship Complete!': '¡Campeonato terminado!',
  'Play Again': 'Volver a jugar',
  'Start Next Race': 'Empezar la siguiente carrera',
  'Failed to load statistics. Please try again.':
    'No se pudieron cargar las estadísticas. Inténtalo de nuevo.',
  'Player statistics': 'Estadísticas del jugador',
  'All-Time': 'Desde el inicio',
  Races: 'Carreras',
  Accuracy: 'Precisión',
  'Favourite operation': 'Operación favorita',
  'Avg response (ms)': 'Tiempo medio de respuesta (ms)',
  'Best streak': 'Mejor racha',
  'Race history': 'Historial de carreras',
  'Recent Races': 'Carreras recientes',
  'No races yet.': 'Aún no hay carreras.',
  Score: 'Puntuación',
  Streak: 'Racha',
  Previous: 'Anterior',
  'Page {{page}} of {{total}}': 'Página {{page}} de {{total}}',
  Level: 'Nivel',
  'Level {{level}} — {{current}} of {{max}} XP': 'Nivel {{level}} — {{current}} de {{max}} XP',
  'Syncing saved Training results…': 'Sincronizando los resultados guardados…',
  'Saved Training results are synced.': 'Los resultados guardados se han sincronizado.',
  'Training results could not sync. They remain saved on this device.':
    'No se pudieron sincronizar los resultados. Siguen guardados en este dispositivo.',
  'Off to the Races!': '¡A correr!',
  'Complete your first race.': 'Completa tu primera carrera.',
  'Perfect Score': 'Puntuación perfecta',
  'Answer all 8 problems correctly in a single race.':
    'Responde correctamente los 8 problemas en una carrera.',
  'Podium Finisher': 'En el podio',
  'Finish in the top 3 in a race.': 'Termina entre los 3 primeros de una carrera.',
  Champion: 'Campeón',
  'Finish in 1st place in a race.': 'Termina en primer lugar en una carrera.',
  'Rising Star': 'Estrella en ascenso',
  'Reach level 5.': 'Alcanza el nivel 5.',
  'Veteran Racer': 'Corredor veterano',
  'Reach level 10.': 'Alcanza el nivel 10.',
  'Math Legend': 'Leyenda de las mates',
  'Reach level 20.': 'Alcanza el nivel 20.',
  'Speed Demon': 'Rayo veloz',
  'Win a race with an average response time under 500ms.':
    'Gana una carrera con un tiempo medio de respuesta inferior a 500 ms.',
};

export const catalogs: Record<Locale, Record<TranslationKey, string>> = {
  en,
  ru,
  es,
};

export function isLocale(value: string): value is Locale {
  return supportedLocales.some((locale) => locale === value);
}

export function resolveLocale(storedLocale: string | null, browserLocale: string | null): Locale {
  if (storedLocale && isLocale(storedLocale)) return storedLocale;
  const language = browserLocale?.toLowerCase().split('-')[0];
  return language && isLocale(language) ? language : 'ru';
}

export function translate(locale: Locale, key: TranslationKey, values?: TranslationValues): string {
  const message = catalogs[locale][key];
  if (!values) return message;
  return message.replace(/\{\{(\w+)\}\}/g, (placeholder, name: string) =>
    Object.prototype.hasOwnProperty.call(values, name) ? String(values[name]) : placeholder,
  );
}

export type { TranslationKey };
